# Generated by Django 2.1.7 on 2019-03-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('postCount', models.IntegerField()),
                ('boardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro_user.Board')),
            ],
            options={
                'ordering': ('updateDate',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth0Id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('birthDate', models.DateField()),
                ('avatar', models.ImageField(upload_to='')),
                ('title', models.CharField(default='New User', max_length=50)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='lastUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lastUser', to='foro_user.User'),
        ),
        migrations.AddField(
            model_name='thread',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='foro_user.User'),
        ),
    ]
