# Generated by Django 2.1.7 on 2019-03-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro_user', '0002_auto_20190301_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='creationDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='lastUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lastUser', to='foro_user.User'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='postCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updateDate',
            field=models.DateTimeField(),
        ),
    ]
