# Generated by Django 2.1.7 on 2019-03-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_user', '0003_auto_20190304_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updateDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
