# Generated by Django 2.1.5 on 2019-03-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro_user', '0004_auto_20190304_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='foro_user.Board'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
